name: Watcher

on:
  workflow_dispatch:
  schedule:
    - cron:  '* 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    # - name: Install dependencies
    #   run: go install
    - name: Run Go
      env:
        WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
        CHANNEL: ${{secrets.CHANNEL}}
        TOKEN: ${{secrets.TOKEN}}
      run: go run main.go
